### ISSUE TITLE
warning: is expected to have version >=2.3.1, but has ; 

### ISSUE THREAD

**Issue by pjoe** [pulumi/pulumi-azure#506]
After latest upgrade I'm getting this:
```
warning: resource plugin azure is expected to have version >=2.3.1, but has ; the wrong version may be on your path, or this may be a bug in the plugin
```

Here is what I have:
```
yarn list --pattern azure
yarn list v1.22.0
warning package.json: No license field
warning tms-pulumi: No license field
├─ @azure/functions@1.2.0
├─ @azure/ms-rest-azure-env@2.0.0
├─ @azure/ms-rest-azure-js@2.0.1
├─ @azure/ms-rest-js@2.0.5
├─ @azure/ms-rest-nodeauth@3.0.3
├─ @pulumi/azure@2.3.1
├─ azure-eventgrid@1.6.0
├─ azure-functions-ts-essentials@1.3.2
└─ ms-rest-azure@2.6.0
✨  Done in 0.22s.
```

I also upgraded azure-cli to 2.3.0 which seems to be the latest available on chocolatey

**Comment by marklam** [comment]
Also with version >=2.4.0-alpha.158559637

**Comment by stack72** [comment]
Hi both

I am sorry that you are getting this error - I am looking for a fix for this right now

Paul

**Comment by pjoe** [comment]
Luckily it is only a warning ... things still work 😄

**Comment by stack72** [comment]
yeah I can see what the issue is :/ Since we moved to the new go modules structure the binary isn't picking up the version. We will have a fix published this afternoon :)

**Comment by rafaribe** [comment]
I'm also getting this error, even asked in the Pulumi slack but nobody could come up with a solution.

**Comment by swoop-alex** [comment]
@stack72 how&when will the fix be available?

thanks!

**Comment by stack72** [comment]
Hi all

I’m currently working to upgrade the provider to the latest codegen so a fix is on its way

I got caught up preparing for the v3.0.0 beta of Pulumi-azure yesterday

Paul

**Comment by stack72** [comment]
Folks, I believe this is solved with https://github.com/pulumi/pulumi-azure/pull/510

I was able to build the binary and copy it to my local plugins directory and there were no warnings around the version

When this gets released, can someone test this for me?

**Comment by swoop-alex** [comment]
sure, waiting for the release

**Comment by stack72** [comment]
Reopening until this is verified

**Comment by stack72** [comment]
@swoop-alex the release has been made - please can you check you are in a better situation? 🙏

**Comment by swoop-alex** [comment]
I did 
`pulumi plugin install resource azure v2.4.0`

then I did update in the package.json  "@pulumi/azure": "^2.4.0"

and then run `pulumi apply`

I still get "warning: resource plugin azure is expected to have version >=2.4.0, but has ; the wrong version may be on your path, or this may be a bug in the plugin"

after that I checked the stack json file and also there the new version is to be seen.

Am I missing something? How should I test this?

**Comment by stack72** [comment]
Ok, I actually did find the error!

**Comment by stack72** [comment]
https://github.com/pulumi/pulumi-azure/pull/511
